
server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/digitalcollier_datasource

user1:
  username: AAA
  password: Gafar001

user2:
  username: BBB
  password: Gafar001


